### ISSUE TITLE
No module named gerber

### ISSUE THREAD

**Issue by dreschpe** [TheAntTeam/TheAntFarm#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]
 - Version [e.g. 10, 18.04 LTS]

**Additional context**  
Add application log files from the folder *app_logs*.   

**Additional context**

**Comment by dreschpe** [comment]
After installing I had to add two missing modules: PySide2 and viSpy. 
If I start I get the error: No module named 'gerber'

**Comment by TheAntTeam** [comment]
Hi @dreschpe, do you have installed all the requirements as described in the [installation](https://github.com/TheAntTeam/TheAntFarm#installation) procedure? Gerber is a module of pcb-tool, one of the python packages required by TheAntFarm and it is present in the requirements.txt file.

**Comment by dreschpe** [comment]
After re - installing all modules from the requirement.txt manually the software starts :-)
