### ISSUE TITLE
I cannot home, reset or unlock the machine

### ISSUE THREAD

**Issue by Geekoid85** [TheAntTeam/TheAntFarm#18]
**Describe the bug**
The bug lies in the machine control section.
When I connect the machine, the serial monitor shows the grbl firmware version as usual.
But when I try to home nothing is happening and there is an error in the windows cmd.
The machine works fine with CncJs so I belive this to be a software bug.

**To Reproduce**
1. Connect the machine
2. Click on home or unlock or reset
3. The machine won't cooperate
4. See error in the windows cmd

**Screenshots**
![image](https://user-images.githubusercontent.com/38323963/167909703-1ef499ec-ec10-4f16-ae7e-05f25d34428e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Latest The Ant Farm version from 11/05/2022

**Comment by TheAntTeam** [comment]
Hello @Geekoid85,
thanks for signaling this issue, it should be solved, I tested the commands and they work again after the last commit.
