### ISSUE TITLE
Plot of deselect GCode not cleared

### ISSUE THREAD

**Issue by alexlinno** [TheAntTeam/TheAntFarm#20]
When having to GCode files loaded selecting one and then the other shows both in the viewport.

**Comment by alexlinno** [comment]
Also I cannot remove GCode fiels from the list

**Comment by TheAntTeam** [comment]
Hi Alex,
thanks for opening this issue.
Could you send us the files you are using? 

If you can also list the packages you have installed in you virtual environment are report them here. The following command should be enough:  
  
> pip list  

Is there a specific sequence of actions that reproduces the issue always?

About removing the gcodes, the rows of the table are selected pressing the numbers, you may select multiple rows and then remove them.

**Comment by TheAntTeam** [comment]
I think the commit 1d6133ad463514815fe7aae19ba247b4e967993b solved the issue.
If it is not so, we will re-open it.
