### ISSUE TITLE
Bottom layer ABL Errors

### ISSUE THREAD

**Issue by bvarner** [TheAntTeam/TheAntFarm#23]
**Describe the bug**
Any time I'm milling a bottom layer (have not tried on top-layer -- will do so later this evening) ABL applies z-coordinates that end up in the positive z-axis range in the top right corner of the board. (See attached photo)

You can see the way the tool is lifting in this photo.
![ABLMillingError](https://user-images.githubusercontent.com/1652015/173701223-8cdd49be-f914-4164-af2f-8d65ed2af0d5.jpg)

**To Reproduce**
Load a bottom gerber, generate a job.
Load the gcode into the control tab. Bottom layer gcode is properly displayed, and the job looks good.
Switch to the sender, connect to machine, set work pos offset on X-Y = 0.
Click "Get BBox", make sure ABL checkbox is selected.
Set ABL step sizes.
Click "ABL"... (I then wait until the finished message shows up in the console.)

Send the GCODE to the ANT.

As the cutter approaches the top-right corner of the board, I consistently get Z WPos in the positive range.
I'm not certain yet, but I think it may be cutting more deeply than I've had the job setup specified to cut.

**Expected behavior**
I expect it not to lift into positive Z axis working space after ABL, when the board clearly warps into the negative space.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version Several releases. Running on python3, in venv.

**Additional context**  
Add application log files from the folder *app_logs*.   

**Additional context**
I plan to re-test this by mirroring the plots from kicad, and generating a set of files I can mill as a 'top' layer instead. I have a sneaking suspicion this has something to do with the 'flip' of the coordinates, but that's just an unproven hun

**Comment by bvarner** [comment]
Can confirm: Top Layers mill isolation routes perfectly.

**Comment by TheAntTeam** [comment]
Ok, the behavior is replicable. Debug in progress

**Comment by TheAntTeam** [comment]
Hi, can you try the fix? I have done some tests and It seems working
