### ISSUE TITLE
Build instructions out of date

### ISSUE THREAD

**Issue by bvarner** [TheAntTeam/TheAntFarm#24]
Following the instructions to setup for a working environment no longer functions since the source was moved to src/TheAntFarm.

**Comment by dreschpe** [comment]
Some tips to fix this?

**Comment by Lichtjaeger** [comment]
> Some tips to fix this?

I got it to work according to the old instructions after coping the `src/TheAntFarm` content back to the project root.

**Comment by TheAntTeam** [comment]
The last commits should have solved this issue, I also updated the Readme.

**Comment by TheAntTeam** [comment]
Updated README with revision 671a09f9933cf82f96f655281d8414b5669b6f1d.
