### ISSUE TITLE
Edge cut routing: Tabs, not Taps.

### ISSUE THREAD

**Issue by bvarner** [TheAntTeam/TheAntFarm#25]
This is probably a translation / transliteration / pronunciation issue. :-)

The English word for the connection between the PCB and the material it was cut from is 'tab' not 'tap'.

**Comment by TheAntTeam** [comment]
Hi, thanks for pointing it out, I guess I wanted to use "gap", and somewhat ended writing "tap".

**Comment by TheAntTeam** [comment]
In the commit 3397466c668462751216c8d71299cc3ca7e6f0d3 I changed the UI to Gap(s). 
I also changed internally in the code where I am sure the change doesn't affect the settings names. There could be some more places to change.

**Comment by bvarner** [comment]
Well, gap makes sense in that there are 'gaps' in the cutting route. So OK!
